### ISSUE TITLE
Dir not found and meta file is still created though.

### ISSUE THREAD

**Issue by alsilva86** [nuxeo/nuxeo-python-client#58] opened 2018-04-18 18:58 UTC
Hello everybody. 
I am trying to validate if a specific directory exists in case it doesn't, we are creating it. Here are few of my considerations:
- Meta file is created using the reference of folders I've specified                                                                file = nuxeo.documents.create(new_file, parent_path=nuxeoConfig['ambiente_cadastro'] + '/' + produto)
- At same time when trying to use your directory search on same folder structure it simply returns me not found I am taking as reference your example/directories.rst:
entries = nuxeo.directories.get('produto')

final question: How can I upload a file use produto variable/ folder structure and can not return its entries using the directories.get?

`import configparser
from nuxeo.models import Document, FileBlob, BufferBlob, DirectoryEntry
from nuxeo.exceptions import UploadError
from nuxeo.client import Nuxeo
from flask import Flask, Blueprint, jsonify
from logging import basicConfig

#log = basicConfig(level='DEBUG')

appConfig = configparser.ConfigParser()
appConfig.read("../config/docsMS.ini")
nuxeoConfig = appConfig['Ambiente_ECM']

def insertCadastro(produto=None, cnpj=None, pdf=None):
    # Connection
    host = nuxeoConfig['host']
    auth = (nuxeoConfig['user'], nuxeoConfig['password'])
    nuxeo = Nuxeo(host=host, auth=auth)
    batch = nuxeo.uploads.batch()
    new_file = Document(
        name=pdf,
        type='File',
        properties={
            'dc:title': pdf
      })
    file = nuxeo.documents.create(new_file, parent_path=nuxeoConfig['ambiente_cadastro'] + '/' + produto)
    print("Testando")
    # Upload a document
    blob = FileBlob(pdf)
    print("================================================")
    #entries = nuxeo.directories.get('testProduct')
    #iprint(entries)
    entries = False
    print("OI")
    try:
        uploaded = batch.upload(blob, chunked=False)
        print(uploaded)
        print("================================================")
    except UploadError:
        print("Erro")
    if not entries:     #PRODUTO NUNCA CADASTRADO
        new_entry = DirectoryEntry(
            properties={
            'id': produto,
            'label': produto,
        })
        entry = nuxeo.directories.get(produto).create(new_entry)
    operation = nuxeo.operations.new('Blob.AttachOnDocument')
    operation.params = {'document': nuxeoConfig['ambiente_cadastro'] +  '/' + produto +  '/' + pdf}
    operation.input_obj = uploaded
    try:
        operation.execute()
    except UploadError:
        print("Erro")
    return jsonify({"status": True})
`

**Comment by BoboTiG** [comment] 2018-04-19 09:17
Could you please format your code, use english everywhere and ask clear questions? Provide minimal example for we can try to reproduce the issue. 
Thank you.

**Comment by BoboTiG** [comment] 2018-05-18 08:46
Closing the issue as no answer since 30 days. Do not hesitate to re-open it with clear content.

**Closed by BoboTiG** 2018-05-18 08:46 UTC
